### ISSUE TITLE
Support escaping for v-i18n-html directive

### ISSUE THREAD

**Issue by iiirxs** [santhoshtr/vue-banana-i18n#9]
v-i18n-html directive is currently vulnerable to XSS attacks. For example, consider a message with a value like this: `"<img src=x onerror=\"alert('XSS Attack')\" >"`. Using `v-i18n-html:message-key` will execute the "dangerous" alert method. 

Solution: HTML sanitize message before assign it to element innerHtml.

**Comment by santhoshtr** [comment]
@iiirxs Can you please help fixing this? Just copying the logic we have in mediawiki.base.js or MW Core for html escaping to here?

**Comment by santhoshtr** [comment]
This is addressed in https://github.com/wikimedia/banana-i18n/pull/50. Need review
